__author__ = "Jonas Almlöf"
__copyright__ = "Copyright 2021, Jonas Almlöf"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/exomedepth.smk"
include: "rules/cnvkit.smk"
include: "rules/cnvkit_vcf.smk"
include: "rules/germline_vcf.smk"
include: "rules/gatk_cnv.smk"
include: "rules/gatk_cnv_vcf.smk"
include: "rules/generate_pindel_config.smk"
include: "rules/manta.smk"
include: "rules/pindel.smk"
include: "rules/svdb.smk"


rule all:
    input:
        unpack(compile_output_list),
