__author__ = "Jonas Almlöf"
__copyright__ = "Copyright 2021, Jonas Almlöf"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/automap.smk"
include: "rules/bgzip.smk"
include: "rules/cnvkit.smk"
include: "rules/cnvpytor.smk"
include: "rules/exomedepth.smk"
include: "rules/expansionhunter.smk"
include: "rules/gatk.smk"
include: "rules/jumble.smk"
include: "rules/manta.smk"
include: "rules/melt.smk"
include: "rules/paraphase.smk"
include: "rules/pindel.smk"
include: "rules/purecn.smk"
include: "rules/reviewer.smk"
include: "rules/sawfish.smk"
include: "rules/scramble.smk"
include: "rules/smncopynumbercaller.smk"
include: "rules/sniffles2.smk"
include: "rules/svdb.smk"
include: "rules/tabix.smk"
include: "rules/tiddit.smk"
include: "rules/trgt.smk"
include: "rules/upd.smk"
include: "rules/xtea.smk"


rule all:
    input:
        unpack(compile_output_list),
