resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:3.0.0"

reference:
  design_bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"
  design_intervals_gatk_cnv: "reference/twist_DNA_solid.HES45.annotated.interval_list"
  fasta: "reference/WASH7P.fna"

automap:
  container: "docker://hydragenetics/automap:1.2"
  build: "hg38"
  extra: "--DP 10 --minsize 3 --chrX"

bwa_mem:
  amb: "reference/WASH7P.fna.amb"
  ann: "reference/WASH7P.fna.ann"
  bwt: "reference/WASH7P.fna.bwt"
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  pac: "reference/WASH7P.fna.pac"
  sa: "reference/WASH7P.fna.sa"

cnvkit_batch:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  method: "hybrid"
  normal_reference: "reference/cnvkit_Twist_PoN_chr1.cnn"

cnvkit_call:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_diagram:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_scatter:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_vcf:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_seg:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvpytor_readdepth:
  container: "docker://hydragenetics/cnvpytor:1.2.1"
  length_list: "10000"

cnvpytor_filter:
  container: "docker://hydragenetics/cnvpytor:1.2.1"
  dG_range: "100000 inf"
  p_range: "0 0.01"
  pN_range: "0 0.5"
  Q0_range: "0 0.05"
  view: "10000"

exomedepth_call:
  bedfile: "reference/twist_DNA_solid.chr1.exomedepth.annotated.bed"
  container: "docker://hydragenetics/exomedepth:1.1.15"
  ref_count: "reference/ref_count.txt"

expansionhunter:
  container: "docker://hydragenetics/expansionhunter:5.0.0"
  variant_catalog: "reference/variant_catalog.json"

gatk_collect_read_counts:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

gatk_denoise_read_counts:
  container: "docker://hydragenetics/gatk4:4.2.2.0"
  normal_reference: "reference/twist_DNA_solid.HES45.GATK_cnv.PoN.hdf5"

gatk_collect_allelic_counts:
  container: "docker://hydragenetics/gatk4:4.2.2.0"
  SNP_interval: "reference/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_model_segments:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

gatk_call_copy_ratio_segments:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

gatk_seq_to_vcf:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

manta_config_t:
  container: "docker://hydragenetics/manta:1.6.0"

manta_config_tn:
  container: "docker://hydragenetics/manta:1.6.0"

manta_config_n:
  container: "docker://hydragenetics/manta:1.6.0"

manta_run_workflow_t:
  container: "docker://hydragenetics/manta:1.6.0"

manta_run_workflow_tn:
  container: "docker://hydragenetics/manta:1.6.0"

manta_run_workflow_n:
  container: "docker://hydragenetics/manta:1.6.0"

melt:
  container: "docker://vanallenlab/melt:3159ce1"
  bed: "reference/Hg38.genes.bed"
  extra: ""
  mei: "reference/mei_list.txt"

pindel_update_vcf:
  container: "docker://hydragenetics/picard:2.25.4"

pindel_call:
  include_bed: "reference/twist_DNA_solid.chr1.annotated.bed"
  container: "docker://hydragenetics/pindel:0.2.5b9"

pindel2vcf:
  container: "docker://hydragenetics/pindel:0.2.5b9"

purecn:
  container: "docker://hydragenetics/purecn:2.2.0"
  genome: "hg19"
  segmentation_method: "GATK4"
  fun_segmentation: "Hclust"
  interval_padding: 100

purecn_coverage:
  container: "docker://hydragenetics/purecn:2.2.0"
  intervals: "reference/purecn_dummy_intervals.txt"

reviewer:
  container: "docker://hydragenetics/reviewer:0.2.7"

svdb_merge:
  cnv_callers:
    - "cnvkit"
    - "gatk"
    - "pindel"
  container: "docker://hydragenetics/svdb:2.6.0"

svdb_query:
  container: "docker://hydragenetics/svdb:2.6.0"
  db_string: "--db reference/normal_26_svdb_0.8.vcf"

tiddit:
  container: "docker://hydragenetics/tiddit:3.3.2"

trimmer_software: "fastp_pe"
